### ISSUE TITLE
Can't push on custom events

### ISSUE THREAD

**Issue by FabienMotte** [Duffleman/pushman#1]
I've created a custom event (for private purposes) named 'auth'.

This is the client part (subscribed to 'auth' channel with his token on the 'test' event) :
![pushman-2](https://cloud.githubusercontent.com/assets/662153/7720875/769c324e-fed2-11e4-9f3a-59a6b72c1260.png)

But when I try to push data on this channel/event, I get nothing back on the client part.
And also, the name of the channel in the JSON response is wrong (always 'public' returned), but the good one is send in the request.
![pushman-1](https://cloud.githubusercontent.com/assets/662153/7720883/912d1a56-fed2-11e4-9d67-59031871c455.png)

Thanks !

**Comment by DuffleOne** [comment]
This has now also been deployed onto the live site. Try now :)

**Comment by FabienMotte** [comment]
Thanks, it works like a charm ! Fantastic tool btw ! :smiley:
