### ISSUE TITLE
unfiltered xss

### ISSUE THREAD

**Issue by dillinghamio** [Duffleman/pushman#3]
``` json
"chat_message": "<  a href=\"javascript:alert('xss')\">click me<\\a>"
```

Not sure if you plan on securing this package that assumingly people will grab and just run with it. But there are a lot of open xss vectors.

**Comment by DuffleOne** [comment]
Thanks for pointing this out, I've been playing around with it and do intend to fix it :)

**Comment by stockhausen** [comment]
hello,

thanks for this really really nice job i prepair for helping you,

i think that you need more protection for XSS

maybe integrate CI XSS helper 
https://github.com/bcit-ci/CodeIgniter/blob/068ab206d84bf1668832988932dc61cfb3103bf8/system/core/Security.php

or only PHP strip_tags()

this is your app so you need to choose if 'event' can have html ?

Best regards.

Fabien.

**Comment by DuffleOne** [comment]
You're correct, more XSS protection is needed than the one I've just implemented. I don't think HTML should be allowed in any event name or payload, so work must be done on it!

I can't implement CodeIgnitors security class directly but I will use as much code from that as I can.

Many thanks Fabien ^^

**Comment by jbrooksuk** [comment]
Check out [Laravel-Security](https://github.com/GrahamCampbell/Laravel-Security/), it may help.

**Comment by stockhausen** [comment]
nice package :+1:
