### ISSUE TITLE
Work with laravel 4

### ISSUE THREAD

**Issue by mamunhq** [Duffleman/pushman#6]
is there any way to use with Laravel 4?

**Comment by DuffleOne** [comment]
This isn't something you can pull into an existing project, you should build this as a new project on a server that runs independently of your site. It works as a middleman for handling websockets.

Check out the [PHP Library](https://github.com/PushmanPHP/pushman_php_library), don't use the service provider but you'll be able to still use the Pushman server to push events independantly of Laravel.

**Comment by MamunHoque** [comment]
Okay fine but can you tell me what’s is server requirement? is need to install any module?

**Comment by DuffleOne** [comment]
[Read the readme file on the github repo](https://github.com/PushmanPHP/pushman).

It'll say you need ZeroMQ the binary from their website, how to install it, how to install the required PHP extension, and how to configure it

https://github.com/PushmanPHP/pushman#official-documentation
