### ISSUE TITLE
White screen, no logs

### ISSUE THREAD

**Issue by purplefish32** [Duffleman/pushman#9]
I have just installed pushman. I have installed the required extentions and set up the DB, but when I browse to localhost:8080, I just get a white screen with no info. Nothing in the logs.
Please excuse my Laravel noobishness.

**Comment by mech-tools** [comment]
Try `chmod -R 777 ./storage`

EDIT : And the dashboard should be located at http://localhost:80 -> good old http standard port unless you use a specific one.

**Comment by DuffleOne** [comment]
You shouldn't visit the 8080 port (assuming that's what you set the PUSHMAN_PUBLIC port to), that is for WebSockets to connect to. You should instead go to the default web port and login via the User interface.

In your case, go straight to http://localhost

Internal Port (default 5555): For TCP connections; dont worry about it
Public port (default 8080): For WebSockets to connect

HTTP (default 80): For your user interface and API connections.
